### ISSUE TITLE
Updates to the Website

### ISSUE THREAD

**Issue by prateekiiest** [codeIIEST/codeIIEST.github.io#1]
Anyone wants to work on improving the website ?

### TODO on the WEBSITE
- [ ] The chapters need to updated to the current 4 chapters
- [ ] Details about each chapter to be updated
- [ ] Details of codeIIEST projects to be updated in the website
- [ ] A bit about previous members of codeIIEST (a sort of details about codeIIEST alumni)

@saugata001 
@adilmah

??

**Comment by AdilMah** [comment]
What kind of improvemnts are to be done??

**Comment by prateekiiest** [comment]
@adilmah
The chapters need to updated to the current 4 chapters

* CC
* OS
* ML
* Security

along with detailed description of each of the sections.

Also recent projects under taken by the club needs to be updated there

**Comment by prateekiiest** [comment]
@xdsarkar
@soubh1k
@palabhi
@sourav1997

help needed for the website.

Please contribute.

@manumeral @swrdfish @smitbose @NilanjanaLodh and others any suggestions for the website now?

**Comment by prateekiiest** [comment]
@saugata001 , I guess I invited you as a member a long time back

**Comment by prateekiiest** [comment]
### TODO on the WEBSITE
- [ ] The chapters need to updated to the current 4 chapters
- [ ] Details about each chapter
- [ ] Project details of codeIIEST projects to be updated in the website

**Comment by prateekiiest** [comment]
@soubh1k see the updated issue here

**Comment by prateekiiest** [comment]
anyone willing to work on this?

**Comment by xdsarkar** [comment]
@prateekiiest I'm up!

**Comment by prateekiiest** [comment]
Thanks @xdsarkar . Could you start working on the above issues?

**Comment by smitbose** [comment]
@prateekiiest was going through the site after quite some time, the "Team" section has only pics of the members. Adding their names would make sense.

Also, the Blog section. Something we had planned from the initiation, but never happened till now :P 
Even I started working on the Algo blog, but couldn't get time to proceed. 

Would be nice to see and Algo, and a Tech blog, Tech as in something actively discussing current enhancement in tech, the kind of discussions we see in websites like TechCrunch.

**Comment by prateekiiest** [comment]
I guess I can update all this after March

**Comment by prateekiiest** [comment]
@indrarahul2013 need to work on this

**Comment by indrarahul** [comment]
Sure !!
